### ISSUE TITLE
Debug issues found in RNP PR #2043 #2044

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/ruby-rnp#90] opened 2023-04-11 02:43 UTC
In these RNP PRs the ruby-rnp tests failed:

* https://github.com/rnpgp/rnp/pull/2043
  * macOS 12: https://github.com/rnpgp/rnp/pull/2043/checks?check_run_id=12636550894
* https://github.com/rnpgp/rnp/pull/2044
  * Cirrus: https://github.com/rnpgp/rnp/actions/runs/4658970625/jobs/8245283474?pr=2044

We need to:
1. See why these instances fail
2. Ensure we test all those platforms on ruby-rnp to catch these errors

**Comment by maxirmx** [comment] 2023-04-11 07:25
**s2k_iterations tests**
https://github.com/rnpgp/rnp/actions/runs/4658970625/jobs/8245283474?pr=2044

This failure is not related to ruby-rnp; this feature occasionally fails in other environments 
(see https://github.com/rnpgp/rnp/issues/2024 -- is the same problem, but I now think that my idea about the root cause is wrong)

I will add my considerations to  https://github.com/rnpgp/rnp/issues/2024

**Comment by maxirmx** [comment] 2023-04-11 07:30
https://github.com/rnpgp/rnp/pull/2043/checks?check_run_id=12636550894
 also fails at s2k_iterations tests
 
 I am closing this issue in favor of https://github.com/rnpgp/rnp/issues/2024

**Closed as completed by maxirmx** 2023-04-11 07:30 UTC
Labels: bug
